# -*- coding: utf-8 -*-
"""outrix_task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Os8NQVODX_qMTjrQSfErQlDPaJmL2ldH

**Stock Market Data analysis**
"""

!pip install yfinance plotly

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import plotly.graph_objs as go

# Download stock data (last 1 year)
ticker = "AAPL"
data = yf.download(ticker, period="1y", interval="1d")

# Show first rows
data.head()

#Explore data
print(data.info())
print(data.describe())

#Plot Closing Price Trend
plt.figure(figsize=(10,6))
plt.plot(data['Close'], label='Closing Price')
plt.title(f"{ticker} Closing Price Trend")
plt.xlabel("Date")
plt.ylabel("Price (USD)")
plt.legend()
plt.show()

#Calculate Moving Averages
data['MA20'] = data['Close'].rolling(window=20).mean()   # 20-day moving average
data['MA50'] = data['Close'].rolling(window=50).mean()   # 50-day moving average

plt.figure(figsize=(12,6))
plt.plot(data['Close'], label='Closing Price', alpha=0.7)
plt.plot(data['MA20'], label='20-Day MA')
plt.plot(data['MA50'], label='50-Day MA')
plt.title(f"{ticker} Price with Moving Averages")
plt.xlabel("Date")
plt.ylabel("Price (USD)")
plt.legend()
plt.show()

#Interactive Plot (Plotly)
fig = go.Figure()
# Candlestick chart
fig.add_trace(go.Candlestick(x=data.index,
                             open=data['Open'],
                             high=data['High'],
                             low=data['Low'],
                             close=data['Close'],
                             name='Candlestick'))
# Moving Averages
fig.add_trace(go.Scatter(x=data.index, y=data['MA20'], mode='lines', name='20-Day MA'))
fig.add_trace(go.Scatter(x=data.index, y=data['MA50'], mode='lines', name='50-Day MA'))

fig.update_layout(title=f"{ticker} Stock Price with Moving Averages",
                  xaxis_title="Date",
                  yaxis_title="Price (USD)",
                  template="plotly_dark")

fig.show()